version: "3.9"
services:
  api:
    container_name: GraphQL_Server
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app

  mysql:
    container_name: MySql_DB
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=graphql_typeorm
      - MYSQL_USER=lm 
      - MYSQL_PASSWORD=lm123456
      - MYSQL_ROOT_PASSWORD=root123456
    volumes:
      - ./sql_data/db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
 
  phpmyadmin:
    container_name: PhpMyAdmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    volumes: 
      - phpMyAdminData:/var/www/html/libraries
      - phpMyAdminThemes:/var/www/html/themes

volumes:
  phpMyAdminData:
  phpMyAdminThemes:
  .:
