version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app

  mysql:
    image: mysql:8.0.32
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - mysqlData:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin:5.2.0-fpm-alpine
    environment:
      PMA_HOST: mysql
    ports:
      - "80:80"
    depends_on:
      - mysql
    volumes: 
      - phpMyAdminData:/var/www/html/libraries
      - phpMyAdminThemes:/var/www/html/themes

volumes:
  mysqlData:
  phpMyAdminData:
  phpMyAdminThemes:
  .:
