version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app

  mysql:
    image: mysql:8.0.32
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_DATABASE=graphql_typeorm
    volumes:
      - ./sql_data/db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
 
  phpmyadmin:
    image: phpmyadmin:5.2.0-fpm-alpine
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    volumes: 
      - phpMyAdminData:/var/www/html/libraries
      - phpMyAdminThemes:/var/www/html/themes

volumes:
  phpMyAdminData:
  phpMyAdminThemes:
  .:
